{
    "nodes": [
        {
            "identifier": "10.2.3.254",
            "name": "10.2.3.254",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "???_to_amazon.co.jp_12",
            "name": "???_to_amazon.co.jp_12",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "???_to_amazon.co.jp_14",
            "name": "???_to_amazon.co.jp_14",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "???_to_dmm.co.jp_8",
            "name": "???_to_dmm.co.jp_8",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "poi6-exhdgy.netforest.ad.jp",
            "name": "poi6-exhdgy.netforest.ad.jp",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "218.45.16.105",
            "name": "218.45.16.105",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "218.45.16.21",
            "name": "218.45.16.21",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "222.230.187.41",
            "name": "222.230.187.41",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "163.139.136.135",
            "name": "163.139.136.135",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "163.139.136.9",
            "name": "163.139.136.9",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "124.83.228.73",
            "name": "124.83.228.73",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "183.79.249.252",
            "name": "183.79.249.252",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "206.72.211.146.any2ix.coresite.com",
            "name": "206.72.211.146.any2ix.coresite.com",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "52.93.92.47",
            "name": "52.93.92.47",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "52.93.92.33",
            "name": "52.93.92.33",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "101.203.88.173",
            "name": "101.203.88.173",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "210.173.176.15",
            "name": "210.173.176.15",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "101.203.88.52",
            "name": "101.203.88.52",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "150.222.90.35",
            "name": "150.222.90.35",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "15.230.152.114",
            "name": "15.230.152.114",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "108.170.242.97",
            "name": "108.170.242.97",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "nrt12s58-in-f3.1e100.net",
            "name": "nrt12s58-in-f3.1e100.net",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "202.72.49.107",
            "name": "202.72.49.107",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "rakuten.co.jp",
            "name": "rakuten.co.jp",
            "meta": {},
            "icon": "./images/router.png"
        },
        {
            "identifier": "a625220b68a39b252.awsglobalaccelerator.com",
            "name": "a625220b68a39b252.awsglobalaccelerator.com",
            "meta": {},
            "icon": "./images/router.png"
        }
    ],
    "links": [
        {
            "source": "52.93.92.47",
            "target": "???_to_amazon.co.jp_12",
            "meta": {
                "domain": "amazon.co.jp"
            }
        },
        {
            "source": "52.93.92.33",
            "target": "???_to_amazon.co.jp_14",
            "meta": {
                "domain": "amazon.co.jp"
            }
        },
        {
            "source": "150.222.90.35",
            "target": "???_to_dmm.co.jp_8",
            "meta": {
                "domain": "dmm.co.jp"
            }
        },
        {
            "source": "10.2.3.254",
            "target": "poi6-exhdgy.netforest.ad.jp",
            "meta": {
                "domain": null
            }
        },
        {
            "source": "poi6-exhdgy.netforest.ad.jp",
            "target": "218.45.16.105",
            "meta": {
                "domain": null
            }
        },
        {
            "source": "poi6-exhdgy.netforest.ad.jp",
            "target": "218.45.16.21",
            "meta": {
                "domain": "rakuten.co.jp"
            }
        },
        {
            "source": "218.45.16.105",
            "target": "222.230.187.41",
            "meta": {
                "domain": null
            }
        },
        {
            "source": "222.230.187.41",
            "target": "163.139.136.135",
            "meta": {
                "domain": "yahoo.co.jp"
            }
        },
        {
            "source": "222.230.187.41",
            "target": "163.139.136.9",
            "meta": {
                "domain": "amazon.co.jp"
            }
        },
        {
            "source": "163.139.136.135",
            "target": "124.83.228.73",
            "meta": {
                "domain": "yahoo.co.jp"
            }
        },
        {
            "source": "124.83.228.73",
            "target": "183.79.249.252",
            "meta": {
                "domain": "yahoo.co.jp"
            }
        },
        {
            "source": "163.139.136.9",
            "target": "206.72.211.146.any2ix.coresite.com",
            "meta": {
                "domain": "amazon.co.jp"
            }
        },
        {
            "source": "206.72.211.146.any2ix.coresite.com",
            "target": "52.93.92.47",
            "meta": {
                "domain": "amazon.co.jp"
            }
        },
        {
            "source": "???_to_amazon.co.jp_12",
            "target": "52.93.92.33",
            "meta": {
                "domain": "amazon.co.jp"
            }
        },
        {
            "source": "218.45.16.105",
            "target": "101.203.88.173",
            "meta": {
                "domain": "google.co.jp"
            }
        },
        {
            "source": "218.45.16.21",
            "target": "210.173.176.15",
            "meta": {
                "domain": "rakuten.co.jp"
            }
        },
        {
            "source": "218.45.16.105",
            "target": "101.203.88.52",
            "meta": {
                "domain": "dmm.co.jp"
            }
        },
        {
            "source": "101.203.88.52",
            "target": "150.222.90.35",
            "meta": {
                "domain": "dmm.co.jp"
            }
        },
        {
            "source": "???_to_dmm.co.jp_8",
            "target": "15.230.152.114",
            "meta": {
                "domain": "dmm.co.jp"
            }
        },
        {
            "source": "101.203.88.173",
            "target": "108.170.242.97",
            "meta": {
                "domain": "google.co.jp"
            }
        },
        {
            "source": "108.170.242.97",
            "target": "nrt12s58-in-f3.1e100.net",
            "meta": {
                "domain": "google.co.jp"
            }
        },
        {
            "source": "210.173.176.15",
            "target": "202.72.49.107",
            "meta": {
                "domain": "rakuten.co.jp"
            }
        },
        {
            "source": "202.72.49.107",
            "target": "rakuten.co.jp",
            "meta": {
                "domain": "rakuten.co.jp"
            }
        },
        {
            "source": "15.230.152.114",
            "target": "a625220b68a39b252.awsglobalaccelerator.com",
            "meta": {
                "domain": "dmm.co.jp"
            }
        }
    ]
}